### ISSUE TITLE
I have unknown bug.

### ISSUE THREAD

**Issue by xGoldenS** [Panthere/GoBot#18]
Here is my log. It get bug at BotInstance.cs:line 273

Initializing Rocket logger at time 7/25/2016 12:26:43 PM...
[12:26:43] Google Token: Auth Token
[12:28:13] Starting Execute on login server: Ptc
[12:28:13] Stop button hit!
[12:28:13] Stop was called!
[12:28:15] Starting Execute on login server: Ptc
[12:28:18] Sorting through 0 pokemon to transfer duplicates...
[12:28:19] Farming 184 PokeStops... True
[12:28:19] Distance to target location: 74.27 meters.
[12:28:19] Sorting through 0 pokemon to transfer duplicates...
[12:28:19] Farming 184 PokeStops... True
[12:28:19] Distance to target location: 74.27 meters.
[12:28:22] Distance to target location: 68.71 meters.
[12:28:23] Distance to target location: 68.71 meters.
[12:28:25] Distance to target location: 47.06 meters.
[12:28:26] Distance to target location: 52.45 meters.
[12:28:28] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:28:29] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:28:29] Sorting through 0 pokemon to transfer duplicates...
[12:28:33] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:28:33] Sorting through 0 pokemon to transfer duplicates...
[12:28:42] Recycled 1x ItemPotion
[12:28:53] Farmed XP: 50, Gems: 0, Eggs:  Items: 1 x ItemPotion, 2 x ItemPokeBall
[12:28:53] Farmed XP: 0, Gems: 0, Eggs:  Items: 
[12:28:57] Distance to target location: 36.57 meters.
[12:28:58] Distance to target location: 33.98 meters.
[12:29:00] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:29:01] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:29:02] We caught a Rattata with CP 282 (63.33% perfection) using a ITEM_POKE_BALL
[12:29:04] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:29:04] Exception in Encounter: System.NullReferenceException: Object reference not set to an instance of an object.
   at GoBot.Logic.BotInstance.<CatchEncounter>d__18.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 273
[12:29:08] Sorting through 0 pokemon to transfer duplicates...
[12:29:28] Distance to target location: 59.5 meters.
[12:29:31] Distance to target location: 53.95 meters.
[12:29:35] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:29:40] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:29:42] We caught a Pidgey with CP 244 (66.67% perfection) using a ITEM_POKE_BALL
[12:29:48] Sorting through 0 pokemon to transfer duplicates...
[12:29:50] Distance to target location: 53.02 meters.
[12:29:53] Distance to target location: 47.46 meters.
[12:29:56] We are within 40 meters of the target. Slowing down to 10 km/h to not pass the target.
[12:29:57] Exception in Encounter: System.NullReferenceException: Object reference not set to an instance of an object.
   at GoBot.Logic.BotInstance.<CatchEncounter>d__18.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 273

**Comment by EnigmaIsWorking** [comment]
I can not compile latest version... Is there a wiki how to config your Branch?

**Comment by xGoldenS** [comment]
You need reset reference to compile :smiley:

**Comment by Panthere** [comment]
@EnigmaIsWorking if you want to compile from the source you must first download the Ferox API and move the compiled DLL's for his API into the debug folder of this bot.

Looks like it might be the encounter probability is null or something. Will add a few more checks.

**Comment by EnigmaIsWorking** [comment]
I downloaded Ferox latest API
By looking on the configs I don't habe to edit something. How can I compile something in your debug folder to your bot? Would be really nice if you could mention that (visual studio 2015 enterprise) ... there is non "export project" into DLL or something like that... In Java I could always make an apk oder .jar ....

**Comment by EnigmaIsWorking** [comment]
I give up. To complicated and to much errors trying to merge Ferox Api with your GUI.
Is there an easier way to use your GUI? (Like Necro Bot... just download, edit settings and run)?

**Comment by Panthere** [comment]
You simply copy and paste the dll's created by Ferox's output into the "/bin/debug" folder of GoBot...
The pre-releases are what you are looking for, they are already compiled from my source, just for people like you :)
