### ISSUE TITLE
Exception (PostLogin): System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by theraperbe** [Panthere/GoBot#25]
Im getting this error when running the bot

> [00:47:26] Looping PostLogin Again - Idle: False
[00:47:28] Sorting through 0 pokemon to evolve...
[00:47:28] Sorting through 0 pokemon to transfer duplicates...
[00:47:28] Farming 216 PokeStops... True
[00:47:28] Exception (PostLogin): System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GoBot.Utils.Navigation.<DirectionalWalking>d__7.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Utils\Navigation.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoBot.Logic.BotInstance.<ExecuteFarmingForts>d__16.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GoBot.Logic.BotInstance.<PostLoginExecute>d__14.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 139

>

**Comment by Panthere** [comment]
Added more checking, will push soon.
Was due to the lack of a route. If that happens it'll just use the standard walk direct.
