### ISSUE TITLE
Event log being flooded with this message

### ISSUE THREAD

**Issue by uk-shahj** [Panthere/GoBot#38]
The bot is working but the event log is being flooded with this message:

Looping PostLogin Again – Idle:False

Exception (PostLogin): PokemonGo.RocketAPI.Exceptions.InvalidReponseException: Exception of type ‘PokemonGo.RocketAPI.Exceptions.InvalidResponseException’ was thrown. At PokemonGo.RocketAPI.Extensions.HttpClientExtensions. <PostProtoPayload>d_0’2.MoveNex

Screenshot: http://i.imgur.com/mId2hOu.png

**Comment by Ikeoth** [comment]
I had that happen as well. Simply waiting and trying again resolved it. Could be a sign of a down or unresponsive server.

**Comment by Nomaan12345** [comment]
I had that happen as well.

**Comment by Panthere** [comment]
Servers down.

**Comment by 66kero66** [comment]
It happens pretty much once a hour for some reason even the server is not down. Every time i have to re-open the GoBot. Thanks for your hard work! Really appreciate it.

**Comment by uk-shahj** [comment]
Here is the full message from the log, might help you with finding the issue:

[12:41:38] Exception (PostLogin): PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`2.MoveNext() in C:\Users\DEDI-ADL-07\Documents\GitHub\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\DEDI-ADL-07\Documents\GitHub\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Inventory.<GetInventory>d__4.MoveNext() in C:\Users\DEDI-ADL-07\Documents\GitHub\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Inventory.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoBot.Logic.Inventory.<GetPokemons>d__8.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\Inventory.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoBot.Logic.Inventory.<GetPokemonToEvolve>d__13.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\Inventory.cs:line 299
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoBot.Logic.BotInstance.<EvolveAllPokemonWithEnoughCandy>d__23.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 467
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GoBot.Logic.BotInstance.<PostLoginExecute>d__14.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 134

The message comes up even when the servers are not down, as 66kero66 mentioned.
