### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Minnette** [Panthere/GoBot#66]
My email uses a non @gmail.com domain, and as such it won't let me log in with the username:password function. Just says:

 "Login Exception: Systeme.IO.FileNotFoundException: Could not load file or assem....
Invalid email/username or password for Google/Ptc Authentication!"

The account still works normally on my phone, but the domain isn't @gmail.com, so I think that may be the issue?

**Comment by Jdf7936** [comment]
I am having a similar issue, but I do have an @gmail and it is still staying:

"Login Exception: Systeme.IO.FileNotFoundException: Could not load file or assem....
 Invalid email/username or password for Google/Ptc Authentication!"

I have tried about 20 times making sure all the information is correct, any solutions would be highly appreciated, Thank you.

**Comment by krazor8** [comment]
make sure for gmail you have 2 step verification off

**Comment by Jdf7936** [comment]
I turned every security feature off and keep getting the same error. The full message I get:

[19:10:49] Google Token: Auth Token
[19:11:30] Starting Execute on login server: Google
[19:11:30] Login Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   at PokemonGo.RocketAPI.Login.GoogleLoginGPSOAuth.DoLogin(String username, String password) in C:\Users\DEDI-ADL-07\Documents\GitHub\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Login\GoogleLoginGPSOAuth.cs:line 17
   at PokemonGo.RocketAPI.Rpc.Login.<DoGoogleLogin>d__1.MoveNext() in C:\Users\DEDI-ADL-07\Documents\GitHub\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GoBot.Logic.BotInstance.<Login>d__17.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 140
[19:11:30] Invalid email/username or password for Google/Ptc Authentication!
[19:11:30] We're out of the loop now, Running is False
[19:11:30] Stopping and walking to start point...
[19:11:30] Exception: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 216.58.216.234:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at GoogleMapsApi.Engine.MapsAPIGenericEngine`2.QueryGoogleAPI(TRequest request, TimeSpan timeout)
   at GoogleMapsApi.EngineFacade`2.Query(TRequest request, TimeSpan timeout)
   at GoogleMapsApi.EngineFacade`2.Query(TRequest request)
   at GoBot.Utils.Navigation.<DirectionalWalking>d__7.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Utils\Navigation.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GoBot.Logic.BotInstance.<WalkToStart>d__19.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GoBot.Logic.BotInstance.<PostLoginExecute>d__18.MoveNext() in C:\Users\DEDI-ADL-07\Documents\Visual Studio 2015\Projects\GoBot\GoBot\Logic\BotInstance.cs:line 204
[19:11:30] Looping Execute Again

Thanks again for any assistance

**Comment by Panthere** [comment]
Looks like an API issue, I can't solve them myself.

**Comment by Minnette** [comment]
Still not working on my google account, working fine on the PTC. Any news?
